### ISSUE TITLE
Not working pod install

### ISSUE THREAD

**Issue by gabdsg** [mcrovero/flutter_interactive_keyboard#1]
The plugin is not working.
`flutter_interactive_keyboard` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by armeaux** [comment]
What is the solution to this?

**Comment by gabdsg** [comment]
> What is the solution to this?

One solution is create the flutter app with `flutter create -i swift package_name`
If you use objective-c... you need to create a swift file in your iOS project and the bridging file.
