### ISSUE TITLE
[FEATURE REQUEST] Allow resizeToAvoidBottomInset to be true

### ISSUE THREAD

**Issue by Haidar-Hammoud** [mcrovero/flutter_interactive_keyboard#12]
Love this library, this was definitely something that should have been included with flutter out of the box.

I've noticed it only works when resizeToAvoidBottomInset is false. It would be great if you could allow for the value to be true that way things stick above the keyboard as it changes its height (e.g. a chat textfield box at the bottom)

**Comment by david-shortman** [comment]
Sounds like a good idea!

This repo is open for pull requests, but not being actively developed/progressed. I'll leave this issue open for someone to see if they'd like to make a contribution to resolve it.

**Comment by Fox520** [comment]
I found this to suit my use case.
In [keyboard_manager.dart](https://github.com/mcrovero/flutter_interactive_keyboard/blob/master/lib/src/keyboard_manager.dart) replace

```dart
var bottom = MediaQuery.of(context).viewInsets.bottom;
```

with

```dart
final viewInsets = EdgeInsets.fromWindowPadding(
        WidgetsBinding.instance!.window.viewInsets,
        WidgetsBinding.instance!.window.devicePixelRatio);
var bottom = viewInsets.bottom;
```

Add this to the ```onKeyboardClose``` callback

```dart
WidgetsBinding.instance?.addPostFrameCallback((_) {
    if (mounted) setState(() {});
 });
```

Credit: https://github.com/maxsalo17/flutter_interactive_keyboard/commit/7f3bedde93a1ed8562613536f7f63836a2128da9
